version: 2

before:
  hooks:
    - go mod tidy

upx:
  - enabled: true
    compress: best
    lzma: true

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - windows
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "taiu-{{ .Os }}-{{ .Arch }}"


changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^style:"
      - "^ci:"
      - "^perf:"
      - "^build:"
      - "^deps:"
      - "^vendor:"
      - "^internal:"
      - "^examples:"

checksum:
  algorithm: sha256
