name: 打包
on:
  push:
    tags:
      - v*

jobs:
  build-and-release:
    name: 开始执行
    runs-on: windows-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: 开始打包
        run: |
          pip install -r requirements.txt
          python -m nuitka --msvc=latest --show-progress --standalone --onefile --assume-yes-for-downloads main.py -o Win64-TAIU.exe

      - name: 获取版本号
        id: get_version
        run: |
          TAG_NAME=$(echo "${{ github.ref }}" | cut -d '/' -f3)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT

      - name: 创建标签
        id: create-tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ steps.get_version.outputs.TAG_NAME }}

      - name: 发布版本
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_version.outputs.TAG_NAME }}
          name: ${{ steps.get_version.outputs.TAG_NAME }}
          files: Win64-TAIU.exe
          token: ${{ secrets.GITHUB_TOKEN }}