name: 打包
on:
  workflow_dispatch:

jobs:
  build-and-release:
    name: 开始执行
    runs-on: windows-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装upx
        run: sudo apt-get install -y upx

      - name: 安装GO
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: 开始打包
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: 'latest'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}