name: 打包
on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    name: 开始执行
    runs-on: windows-latest
    steps:
      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 配置Python环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'

      - name: 开始打包
        run: |
          pip install -r requirements.txt
          python -m nuitka --mingw64 --show-progress --standalone --onefile --assume-yes-for-downloads main.py -o Win64-TAIU.exe

      - name: 获取项目信息
        id: version
        run: |
          VERSION=$(node -p 'require("./package.json").version')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT

      - name: 创建标签
        id: create-tag
        uses: pkgdeps/git-tag-action@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          version: ${{ steps.version.outputs.version }}

      - name: 发布版本
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: ${{ steps.version.outputs.version }}
          files: Win64-TAIU.exe
          token: ${{ secrets.GITHUB_TOKEN }}